# Generated by Django 2.2.4 on 2021-02-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
